exclude: "^$|venv|.direnv"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.0
    hooks:
      - id: tofu_fmt
