on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        id: init
        run: tofu -chdir=infra init

      - name: OpenTofu Plan
        id: plan
        run: tofu -chdir=infra plan -no-color
